name: Publish-TestPyPI

on:
  push:
    tags:
      - "v*"

jobs:
  verify:
    name: Verify tag is on main branch
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Verify tag is valid by git CLI
        run: |
          git fetch origin main
          git merge-base --is-ancestor ${{ github.sha }} origin/main || (echo "Error: Tag is not on main branch" && exit 1)

  build:
    name: Build distribution package
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.10.9"

      - name: Set up Python
        run: uv python install 3.14

      - name: Run uv build
        run: uv build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  publish-TestPyPI:
    name: Publish to TestPyPI
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Publish distribution to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          username: __token__
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
